{% set name = "libmatio" %}
{% set version = "1.5.28" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: matio-{{ version }}.tar.gz
  url: https://github.com/tbeu/matio/releases/download/v{{ version }}/matio-{{ version }}.tar.gz
  md5: a07c6ca0686578057fa452efca4ae558

build:
  number: 1
  skip: true  # [win and (vc<14 or win32)]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - hdf5
    - zlib
  run:
    - hdf5
    - zlib

test:
  commands:
    - test -e $PREFIX/include/matio.h      # [unix]
    - test -e $PREFIX/lib/libmatio.a       # [unix]
    - test -e $PREFIX/lib/libmatio.so      # [linux]
    - test -e $PREFIX/lib/libmatio.dylib   # [osx]
    - if not exist %PREFIX%\Library\bin\libmatio.dll exit 1  # [win]
    - if not exist %PREFIX%\Library\lib\libmatio.lib exit 1  # [win]
    - if not exist %PREFIX%\Library\include\matio.h exit 1  # [win]

about:
  home: https://sourceforge.net/projects/matio
  license: BSD-2-Clause
  license_file: COPYING
  summary: A C library for reading and writing MATLAB MAT files.

extra:
  recipe-maintainers:
    - 183amir
    - tbeu
    - traversaro
